version: 2
updates:

- package-ecosystem: npm
  versioning-strategy: increase
  directory: "/"
  schedule:
    interval: "weekly"
  allow:
    - dependency-type: "all"
  commit-message:
    prefix: "chore:"
  assignees:
    - "AdeAttwood"

- package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    commit-message:
      prefix: 'chore:'
    assignees:
      - 'AdeAttwood'
